services:
  - type: web
    name: tzeva-dashboard
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 -b 0.0.0.0:$PORT tzeva_sirens_dashboard:app
